language: python

before_script:
  - pip install coveralls

python:
    - "3.4"
    - "3.5"
    - "3.6"
 
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO=https://github.com/django/django/archive/master.tar.gz
 
install:
    - pip install django==$DJANGO_VERSION
 
script:
    - coverage run --source myapp setup.py test

after_success:
    - coveralls